name: ci/cd to Prod(sepolia)
on:
  push:
    branches: 
      - main
    tags:
      - '*.*.*'

jobs:
  ci:
    outputs:
      docker-tag: ${{ steps.prepare.outputs.docker-tag }}
      target-cluster: ${{ steps.prepare.outputs.target-cluster }}

    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Prepare
        id: prepare
        run: |
          if [[ $GITHUB_REF_TYPE == 'branch' ]];
          then
            echo "docker-tag=pre-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT
          else
            echo "docker-tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Publish Kroma Prover Proxy
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: kromanetwork/prover-proxy:${{ steps.prepare.outputs.docker-tag }},kromanetwork/prover-proxy:latest
          platforms: linux/amd64,linux/arm64

  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          repository: kroma-network/devops-helm
          ref: main
          token: ${{ secrets.KROMA_GIT_TOKEN }}

      - name: Update Image Tag
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq -i '.image.tag = "${{ needs.ci.outputs.docker-tag }}"' 'kroma-chain/prover-proxy/prod-kroma-sepolia-apne2.yaml'

      - name: Push Changed Image Tag
        run: |
          git config --global user.email lightscale@lightscale.io
          git config --global user.name lightscale
          git config --global push.default matching
          git fetch && git checkout main

          if [ -z "$(git status --porcelain)" ]
          then
            echo "Nothing to commit, working directory clean"
          else
            git commit -am "https://github.com/${{ github.repository }}/commit/${GITHUB_SHA}" && git push
          fi
        shell: bash
