name: ci
on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Prepare
        id: prepare
        run: |
          if [[ $GITHUB_REF_TYPE == 'branch' ]];
          then
            echo "docker-tag=pre-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT
          else
            echo "docker-tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Publish Kroma Prover Proxy
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: kromanetwork/prover-proxy:${{ steps.prepare.outputs.docker-tag }},kromanetwork/prover-proxy:latest
          platforms: linux/amd64,linux/arm64
